/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  pitch_xxsubmod.c
 *  subm:  PositionControllerTilt
 *  model: PositionControllerTilt
 *  expmt: Jiwy-1
 *  date:  June 2, 2025
 *  time:  10:23:18 AM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "pitch_xxmodel.h"
#include "pitch_xxinteg.h"
#include "pitch_xxfuncs.h"
#include "pitch_xxsubmod.h"
#include "pitch_motionprofiles.h"
#include "pitch_EulerAngles.h"

/* The submodel I/O variables */
PITCH_XXInteger pitch_xx_number_of_inputs = 3;
PITCH_XXInteger pitch_xx_number_of_outputs = 1;

/* the names of the submodel io variables
   uncomment this part if you need these names
PITCH_XXString pitch_xx_input_names[] = {
	"corr",
	"in",
	"position"
,	NULL
};
PITCH_XXString pitch_xx_output_names[] = {
	"out"
,	NULL
};
*/
/* This function sets the input variables from the input vector */
void PITCH_XXCopyInputsToVariables (PITCH_XXDouble *u)
{
	/* Copy the input vector to the input variables */
	pitch_xx_V[8] = u[0];		/* corr */
	pitch_xx_V[9] = u[1];		/* in */
	pitch_xx_V[10] = u[2];		/* position */

}

/* This function uses the output variables to fill the output vector */
void PITCH_XXCopyVariablesToOutputs (PITCH_XXDouble *y)
{
	/* Copy the output variables to the output vector */
	y[0] = 	pitch_xx_V[11];		/* out */

}

/* The initialization function for submodel */
void PITCH_XXInitializeSubmodel (PITCH_XXDouble *u, PITCH_XXDouble *y, PITCH_XXDouble t)
{
	/* Initialization phase (allocating memory) */
	pitch_xx_initialize = PITCH_XXTRUE;
	pitch_xx_steps = 0;
	PITCH_XXModelInitialize ();
	PITCH_XXDiscreteInitialize ();

	/* Copy the inputs */
	pitch_xx_time = t;
	PITCH_XXCopyInputsToVariables (u);

	/* Calculate the model for the first time */
	PITCH_XXCalculateInitial ();
	PITCH_XXCalculateStatic ();
	PITCH_XXCalculateInput ();
	PITCH_XXCalculateDynamic ();
	PITCH_XXCalculateOutput ();

	/* Set the outputs */
	PITCH_XXCopyVariablesToOutputs (y);

	/* End of initialization phase */
	pitch_xx_initialize = PITCH_XXFALSE;
}

/* The function that calculates the submodel */
void PITCH_XXCalculateSubmodel (PITCH_XXDouble *u, PITCH_XXDouble *y, PITCH_XXDouble t)
{
	/* Copy the inputs */
	pitch_xx_time = t;
	PITCH_XXCopyInputsToVariables (u);

	/* Calculate the model */
	PITCH_XXCalculateInput ();
	PITCH_XXDiscreteStep ();
	PITCH_XXCalculateOutput ();

	/* Copy the outputs */
	PITCH_XXCopyVariablesToOutputs (y);
}

/* The termination function for submodel */
void PITCH_XXTerminateSubmodel (PITCH_XXDouble *u, PITCH_XXDouble *y, PITCH_XXDouble t)
{
	/* Copy the inputs */
	pitch_xx_time = t;
	PITCH_XXCopyInputsToVariables (u);

	/* Calculate the final model equations */
	PITCH_XXCalculateFinal ();

	/* Set the outputs */
	PITCH_XXCopyVariablesToOutputs (y);

	/* and terminate the model itself (releasing memory) */
	PITCH_XXModelTerminate ();
	PITCH_XXDiscreteTerminate ();
}

