/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yaw_xxinteg.c
 *  subm:  PositionControllerPan
 *  model: PositionControllerPan
 *  expmt: Jiwy-1
 *  date:  June 2, 2025
 *  time:  10:24:36 AM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file describes the integration methods
   that are supplied for computation.

   Currently the following methods are supported:
   * Discrete
   * Euler
   * RungeKutta2
   * RungeKutta4
   but it is easy for the user to add their own
   integration methods with these as examples.
*/

/* the system include files */
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* our own include files */
#include "yaw_xxinteg.h"
#include "yaw_xxmodel.h"

/* global variables prototypes */
extern YAW_XXDouble yaw_xx_time;
extern YAW_XXDouble yaw_xx_step_size;

#define yaw_xx_STATE_SIZE 3

/*********************************************************************
 * Discrete integration method
 *********************************************************************/

/* the initialization of the Discrete integration method */
void YAW_XXDiscreteInitialize (void)
{
	/* nothing to be done */
	yaw_xx_major = YAW_XXTRUE;
}

/* the termination of the Discrete integration method */
void YAW_XXDiscreteTerminate (void)
{
	/* nothing to be done */
}

/* the Discrete integration method itself */
void YAW_XXDiscreteStep (void)
{
	YAW_XXInteger index;

	/* for each of the supplied states */
	for (index = 0; index < yaw_xx_STATE_SIZE; index++)
	{
		/* just a move of the new state */
		yaw_xx_s [index] = yaw_xx_R [index];
	}
	/* increment the simulation time */
	yaw_xx_time += yaw_xx_step_size;

	yaw_xx_major = YAW_XXTRUE;

	/* evaluate the dynamic part to calculate the new rates */
	YAW_XXCalculateDynamic ();
}

