/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yaw_xxmodel.c
 *  model: PositionControllerPan
 *  expmt: Jiwy-1
 *  date:  June 2, 2025
 *  time:  10:24:36 AM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file contains the actual model variables and equations */

/* Note: Alias variables are the result of full optimization
   of the model in 20-sim. As a result, only the real variables
   are used in the model for speed. The user may also include
   the alias variables by adding them to the end of the array:

   YAW_XXDouble yaw_xx_variables[NUMBER_VARIABLES + NUMBER_ALIAS_VARIABLES + 1];
   YAW_XXString yaw_xx_variable_names[] = {
     VARIABLE_NAMES, ALIAS_VARIABLE_NAMES, NULL
   };

   and calculate them directly after the output equations:

   void YAW_XXCalculateOutput (void)
   {
     OUTPUT_EQUATIONS
     ALIAS_EQUATIONS
   }
*/

/* system include files */
#include <stdlib.h>
#include <math.h>
#include <string.h>

/* 20-sim include files */
#include "yaw_xxmodel.h"
#include "yaw_xxfuncs.h"

/* the global variables */
YAW_XXDouble yaw_xx_start_time = 0.0;
YAW_XXDouble yaw_xx_finish_time = 20.0;
YAW_XXDouble yaw_xx_step_size = 0.01;
YAW_XXDouble yaw_xx_time = 0.0;
YAW_XXInteger yaw_xx_steps = 0;
YAW_XXBoolean yaw_xx_initialize = YAW_XXTRUE;
YAW_XXBoolean yaw_xx_major = YAW_XXTRUE;
YAW_XXBoolean yaw_xx_stop_simulation = YAW_XXFALSE;

/* the variable arrays */
YAW_XXDouble yaw_xx_P[yaw_xx_parameters_size];		/* parameters */
YAW_XXDouble yaw_xx_I[yaw_xx_initialvalues_size];		/* initial values */
YAW_XXDouble yaw_xx_V[yaw_xx_variables_size];		/* variables */
YAW_XXDouble yaw_xx_s[yaw_xx_states_size];		/* states */
YAW_XXDouble yaw_xx_R[yaw_xx_states_size];		/* rates (or new states) */

/* the names of the variables as used in the arrays above
   uncomment this part if these names are needed
YAW_XXString yaw_xx_parameter_names[] = {
	"corrGain\\K",
	"PID1\\kp",
	"PID1\\tauD",
	"PID1\\beta",
	"PID1\\tauI",
	"SignalLimiter2\\minimum",
	"SignalLimiter2\\maximum"
,	NULL
};
YAW_XXString yaw_xx_initial_value_names[] = {
	"PID1\\uD_previous_initial",
	"PID1\\error_previous_initial",
	"PID1\\uI_previous_initial"
,	NULL
};
YAW_XXString yaw_xx_variable_names[] = {
	"corrGain\\corr",
	"PID1\\output",
	"",
	"PlusMinus1\\plus1",
	"SignalLimiter2\\output",
	"Splitter1\\input",
	"corr",
	"in",
	"position",
	"out"
,	NULL
};
YAW_XXString yaw_xx_state_names[] = {
	"PID1\\uD_previous",
	"PID1\\error_previous",
	"PID1\\uI_previous"
,	NULL
};
YAW_XXString yaw_xx_rate_names[] = {
	"",
	"PID1\\error",
	""
,	NULL
};
*/

#if (7 > 8192) && defined _MSC_VER
#pragma optimize("", off)
#endif
void YAW_XXModelInitialize_parameters(void)
{
	/* set the parameters */
	yaw_xx_P[0] = 0.0;		/* corrGain\K */
	yaw_xx_P[1] = 2.6;		/* PID1\kp */
	yaw_xx_P[2] = 0.05;		/* PID1\tauD */
	yaw_xx_P[3] = 0.17;		/* PID1\beta */
	yaw_xx_P[4] = 9.0;		/* PID1\tauI */
	yaw_xx_P[5] = -0.99;		/* SignalLimiter2\minimum */
	yaw_xx_P[6] = 0.99;		/* SignalLimiter2\maximum */

}
#if (7 > 8192) && defined _MSC_VER
#pragma optimize("", on)
#endif

void YAW_XXModelInitialize_initialvalues(void)
{
	/* set the initial values */
	yaw_xx_I[0] = 0.0;		/* PID1\uD_previous_initial */
	yaw_xx_I[1] = 0.0;		/* PID1\error_previous_initial */
	yaw_xx_I[2] = 0.0;		/* PID1\uI_previous_initial */

}

void YAW_XXModelInitialize_states(void)
{
	/* set the states */
	yaw_xx_s[0] = yaw_xx_I[0];		/* PID1\uD_previous */
	yaw_xx_s[1] = yaw_xx_I[1];		/* PID1\error_previous */
	yaw_xx_s[2] = yaw_xx_I[2];		/* PID1\uI_previous */

}

void YAW_XXModelInitialize_variables(void)
{
	/* initialize the variable memory to zero */
	memset(yaw_xx_V, 0, yaw_xx_variables_size * sizeof(YAW_XXDouble));
}

/* this method is called before calculation is possible */
void YAW_XXModelInitialize (void)
{
	YAW_XXModelInitialize_parameters();
	YAW_XXModelInitialize_variables();
	YAW_XXModelInitialize_initialvalues();
	YAW_XXModelInitialize_states();
}

/* This function calculates the initial equations of the model.
 * These equations are calculated before anything else
 */
void YAW_XXCalculateInitial (void)
{

	/* set the states again, they might have changed in the initial calculation */
	YAW_XXModelInitialize_states ();
}

/* This function calculates the static equations of the model.
 * These equations are only dependent from parameters and constants
 */
void YAW_XXCalculateStatic (void)
{

}

/* This function calculates the input equations of the model.
 * These equations are dynamic equations that must not change
 * in calls from the integration method (like random and delay).
 */
void YAW_XXCalculateInput (void)
{

}

/* This function calculates the dynamic equations of the model.
 * These equations are called from the integration method
 * to calculate the new model rates (that are then integrated).
 */
void YAW_XXCalculateDynamic (void)
{
	/* PID1\factor = 1 / (sampletime + PID1\tauD * PID1\beta); */
	yaw_xx_V[2] = 1.0 / (yaw_xx_step_size + yaw_xx_P[2] * yaw_xx_P[3]);

	/* PlusMinus1\plus1 = in; */
	yaw_xx_V[3] = yaw_xx_V[7];

	/* Splitter1\input = position; */
	yaw_xx_V[5] = yaw_xx_V[8];

	/* corrGain\corr = corrGain\K * Splitter1\input; */
	yaw_xx_V[0] = yaw_xx_P[0] * yaw_xx_V[5];

	/* PID1\error = PlusMinus1\plus1 - Splitter1\input; */
	yaw_xx_R[1] = yaw_xx_V[3] - yaw_xx_V[5];

	/* PID1\uD = PID1\factor * (((PID1\tauD * PID1\uD_previous) * PID1\beta + (PID1\tauD * PID1\kp) * (PID1\error - PID1\error_previous)) + (sampletime * PID1\kp) * PID1\error); */
	yaw_xx_R[0] = yaw_xx_V[2] * (((yaw_xx_P[2] * yaw_xx_s[0]) * yaw_xx_P[3] + (yaw_xx_P[2] * yaw_xx_P[1]) * (yaw_xx_R[1] - yaw_xx_s[1])) + (yaw_xx_step_size * yaw_xx_P[1]) * yaw_xx_R[1]);

	/* PID1\uI = PID1\uI_previous + (sampletime * PID1\uD) / PID1\tauI; */
	yaw_xx_R[2] = yaw_xx_s[2] + (yaw_xx_step_size * yaw_xx_R[0]) / yaw_xx_P[4];

	/* PID1\output = PID1\uI + PID1\uD; */
	yaw_xx_V[1] = yaw_xx_R[2] + yaw_xx_R[0];

	/* SignalLimiter2\output = if PID1\output < SignalLimiter2\minimum... ; */
	yaw_xx_V[4] = ((yaw_xx_V[1] < yaw_xx_P[5]) ? 
		/* SignalLimiter2\minimum */
		yaw_xx_P[5]
	:
		/* if PID1\output > SignalLimiter2\maximum...  */
		((yaw_xx_V[1] > yaw_xx_P[6]) ? 
			/* SignalLimiter2\maximum */
			yaw_xx_P[6]
		:
			/* PID1\output */
			yaw_xx_V[1]
		)
	);


	/* increment the step counter */
	yaw_xx_steps++;
}

/* This function calculates the output equations of the model.
 * These equations are not needed for calculation of the rates
 * and are kept separate to make the dynamic set of equations smaller.
 * These dynamic equations are called often more than one time for each
 * integration step that is taken. This makes model computation much faster.
 */
void YAW_XXCalculateOutput (void)
{
	/* corr = corrGain\corr; */
	yaw_xx_V[6] = yaw_xx_V[0];

	/* out = SignalLimiter2\output; */
	yaw_xx_V[9] = yaw_xx_V[4];

}

/* This function calculates the final equations of the model.
 * These equations are calculated after all the calculations
 * are performed
 */
void YAW_XXCalculateFinal (void)
{

}

/* this method is called after all calculations are performed */
void YAW_XXModelTerminate(void)
{
}

