/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yaw_xxsubmod.c
 *  subm:  PositionControllerPan
 *  model: PositionControllerPan
 *  expmt: Jiwy-1
 *  date:  June 2, 2025
 *  time:  10:24:36 AM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "yaw_xxmodel.h"
#include "yaw_xxinteg.h"
#include "yaw_xxfuncs.h"
#include "yaw_xxsubmod.h"
#include "yaw_motionprofiles.h"
#include "yaw_EulerAngles.h"

/* The submodel I/O variables */
YAW_XXInteger yaw_xx_number_of_inputs = 2;
YAW_XXInteger yaw_xx_number_of_outputs = 2;

/* the names of the submodel io variables
   uncomment this part if you need these names
YAW_XXString xx_input_names[] = {
	"in",
	"position"
,	NULL
};
YAW_XXString yaw_xx_output_names[] = {
	"corr",
	"out"
,	NULL
};
*/
/* This function sets the input variables from the input vector */
void YAW_XXCopyInputsToVariables (YAW_XXDouble *u)
{
	/* Copy the input vector to the input variables */
	yaw_xx_V[7] = u[0];		/* in */
	yaw_xx_V[8] = u[1];		/* position */

}

/* This function uses the output variables to fill the output vector */
void YAW_XXCopyVariablesToOutputs (YAW_XXDouble *y)
{
	/* Copy the output variables to the output vector */
	y[0] = 	yaw_xx_V[6];		/* corr */
	y[1] = 	yaw_xx_V[9];		/* out */

}

/* The initialization function for submodel */
void YAW_XXInitializeSubmodel (YAW_XXDouble *u, YAW_XXDouble *y, YAW_XXDouble t)
{
	/* Initialization phase (allocating memory) */
	yaw_xx_initialize = YAW_XXTRUE;
	yaw_xx_steps = 0;
	YAW_XXModelInitialize ();
	YAW_XXDiscreteInitialize ();

	/* Copy the inputs */
	yaw_xx_time = t;
	YAW_XXCopyInputsToVariables (u);

	/* Calculate the model for the first time */
	YAW_XXCalculateInitial ();
	YAW_XXCalculateStatic ();
	YAW_XXCalculateInput ();
	YAW_XXCalculateDynamic ();
	YAW_XXCalculateOutput ();

	/* Set the outputs */
	YAW_XXCopyVariablesToOutputs (y);

	/* End of initialization phase */
	yaw_xx_initialize = YAW_XXFALSE;
}

/* The function that calculates the submodel */
void YAW_XXCalculateSubmodel (YAW_XXDouble *u, YAW_XXDouble *y, YAW_XXDouble t)
{
	/* Copy the inputs */
	yaw_xx_time = t;
	YAW_XXCopyInputsToVariables (u);

	/* Calculate the model */
	YAW_XXCalculateInput ();
	YAW_XXDiscreteStep ();
	YAW_XXCalculateOutput ();

	/* Copy the outputs */
	YAW_XXCopyVariablesToOutputs (y);
}

/* The termination function for submodel */
void YAW_XXTerminateSubmodel (YAW_XXDouble *u, YAW_XXDouble *y, YAW_XXDouble t)
{
	/* Copy the inputs */
	yaw_xx_time = t;
	YAW_XXCopyInputsToVariables (u);

	/* Calculate the final model equations */
	YAW_XXCalculateFinal ();

	/* Set the outputs */
	YAW_XXCopyVariablesToOutputs (y);

	/* and terminate the model itself (releasing memory) */
	YAW_XXModelTerminate ();
	YAW_XXDiscreteTerminate ();
}

