/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  pitch_xxsubmod.h
 *  subm:  PositionControllerTilt
 *  model: PositionControllerTilt
 *  expmt: Jiwy-1
 *  date:  June 2, 2025
 *  time:  10:23:18 AM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the pitch_xxmodel.c file
*/

#ifndef PITCH_XX_SUBMOD_H
#define PITCH_XX_SUBMOD_H

/* Our own include files */
#include "pitch_xxmodel.h"

/* Submodel I/O variables */
extern PITCH_XXInteger pitch_xx_number_of_inputs;
extern PITCH_XXInteger pitch_xx_number_of_outputs;

/* The names of the variables as used in the arrays above */
extern PITCH_XXString pitch_xx_input_names[];
extern PITCH_XXString pitch_xx_output_names[];


/* The submodel functions */
void PITCH_XXInitializeSubmodel (PITCH_XXDouble *u, PITCH_XXDouble *y, PITCH_XXDouble t);
void PITCH_XXCalculateSubmodel (PITCH_XXDouble *u, PITCH_XXDouble *y, PITCH_XXDouble t);
void PITCH_XXTerminateSubmodel (PITCH_XXDouble *u, PITCH_XXDouble *y, PITCH_XXDouble t);
void PITCH_XXCopyInputsToVariables (PITCH_XXDouble *u);
void PITCH_XXCopyVariablesToOutputs (PITCH_XXDouble *y);

#endif

