/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  pitch_xxinteg.h
 *  model: PositionControllerTilt
 *  expmt: Jiwy-1
 *  date:  June 2, 2025
 *  time:  10:23:18 AM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file describes the integration methods
that are supplied for computation.

   Currently the following methods are supported:
   * Euler
   * RungeKutta2
   * RungeKutta4
   but it is easy for the user to add their own
   integration methods with these two as an example.
*/

#ifndef PITCH_XX_INTEG_H
#define PITCH_XX_INTEG_H

/* 20-sim include files */
#include "pitch_xxtypes.h"

/* the chosen integration method */
#define Discrete_METHOD

/* the integration methods */
void PITCH_XXDiscreteInitialize (void);
void PITCH_XXDiscreteTerminate (void);
void PITCH_XXDiscreteStep (void);

extern PITCH_XXBoolean pitch_xx_major;

#endif

