/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  pitch_xxmodel.h
 *  subm:  PositionControllerTilt
 *  model: PositionControllerTilt
 *  expmt: Jiwy-1
 *  date:  June 2, 2025
 *  time:  10:23:18 AM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the pitch_xxmodel.c file
*/

#ifndef PITCH_XX_MODEL_H
#define PITCH_XX_MODEL_H

/* Our own include files */
#include "pitch_xxtypes.h"

/* Simulation variables */
extern PITCH_XXDouble pitch_xx_start_time;
extern PITCH_XXDouble pitch_xx_finish_time;
extern PITCH_XXDouble pitch_xx_step_size;
extern PITCH_XXDouble pitch_xx_time;
extern PITCH_XXInteger pitch_xx_steps;
extern PITCH_XXBoolean pitch_xx_initialize;
extern PITCH_XXBoolean pitch_xx_major;
extern PITCH_XXBoolean pitch_xx_stop_simulation;

/* Model size constants */
#define pitch_xx_constants_size 0
#define pitch_xx_parameters_size 7
#define pitch_xx_initialvalues_size 3
#define pitch_xx_variables_size 12
#define pitch_xx_states_size 3

/* Variable arrays */
extern PITCH_XXDouble pitch_xx_P[];
extern PITCH_XXDouble pitch_xx_I[];
extern PITCH_XXDouble pitch_xx_V[];
extern PITCH_XXDouble pitch_xx_s[];
extern PITCH_XXDouble pitch_xx_R[];


/* The names of the variables as used in the arrays above
   uncomment this if you need the names (see source file too)
extern PITCH_XXString pitch_xx_parameter_names[];
extern PITCH_XXString pitch_xx_initial_value_names[];
extern PITCH_XXString pitch_xx_variable_names[];
extern PITCH_XXString pitch_xx_state_names[];
extern PITCH_XXString pitch_xx_rate_names[];
*/

/* Initialization methods */
/* Initialize complete model */
void PITCH_XXModelInitialize (void);
/* Initialize specific model values */
void PITCH_XXModelInitialize_parameters(void);
void PITCH_XXModelInitialize_initialvalues(void);
void PITCH_XXModelInitialize_states(void);
void PITCH_XXModelInitialize_variables(void);
void PITCH_XXModelTerminate (void);

/* Computation methods */
void PITCH_XXCalculateInitial (void);
void PITCH_XXCalculateStatic (void);
void PITCH_XXCalculateInput (void);
void PITCH_XXCalculateDynamic (void);
void PITCH_XXCalculateOutput (void);
void PITCH_XXCalculateFinal (void);


#endif

