/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  pitch_xxfuncs.h
 *  model: PositionControllerTilt
 *  expmt: Jiwy-1
 *  date:  June 2, 2025
 *  time:  10:23:18 AM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

#ifndef PITCH_XX_FUNCS_H
#define PITCH_XX_FUNCS_H

/* Our own include files */
#include "pitch_xxtypes.h"

/* Global constants */
extern PITCH_XXBoolean pitch_xx_initialize;
extern PITCH_XXBoolean pitch_xx_major;
extern PITCH_XXBoolean pitch_xx_stop_simulation;

/* Wrapper functions around strings */
PITCH_XXDouble PITCH_XXString2Double(const char* argument);
const char* PITCH_XXDouble2String(PITCH_XXDouble argument);

/* 20-sim function prototypes */
/* 20-sim stub prototypes */
#endif

