/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  motionprofiles.h
 *  model: PositionControllerPan
 *  expmt: Jiwy-1
 *  date:  June 2, 2025
 *  time:  10:24:36 AM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
