/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yaw_xxfuncs.h
 *  model: PositionControllerPan
 *  expmt: Jiwy-1
 *  date:  June 2, 2025
 *  time:  10:24:36 AM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

#ifndef YAW_XX_FUNCS_H
#define YAW_XX_FUNCS_H

/* Our own include files */
#include "yaw_xxtypes.h"

/* Global constants */
extern YAW_XXBoolean yaw_xx_initialize;
extern YAW_XXBoolean yaw_xx_major;
extern YAW_XXBoolean yaw_xx_stop_simulation;

/* Wrapper functions around strings */
YAW_XXDouble YAW_XXString2Double(const char* argument);
const char* YAW_XXDouble2String(YAW_XXDouble argument);

/* 20-sim function prototypes */
/* 20-sim stub prototypes */
#endif

