/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yaw_xxinteg.h
 *  model: PositionControllerPan
 *  expmt: Jiwy-1
 *  date:  June 2, 2025
 *  time:  10:24:36 AM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file describes the integration methods
that are supplied for computation.

   Currently the following methods are supported:
   * Euler
   * RungeKutta2
   * RungeKutta4
   but it is easy for the user to add their own
   integration methods with these two as an example.
*/

#ifndef YAW_XX_INTEG_H
#define YAW_XX_INTEG_H

/* 20-sim include files */
#include "yaw_xxtypes.h"

/* the chosen integration method */
#define Discrete_METHOD

/* the integration methods */
void YAW_XXDiscreteInitialize (void);
void YAW_XXDiscreteTerminate (void);
void YAW_XXDiscreteStep (void);

extern YAW_XXBoolean yaw_xx_major;

#endif

