/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yaw_xxtypes.h
 *  model: PositionControllerPan
 *  expmt: Jiwy-1
 *  date:  June 2, 2025
 *  time:  10:24:36 AM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file describes the typedefs that are used for integers and
   doubles. All the generated code uses these typedefs to enhance
   flexibility (in case the compiler is not Visual C++ 6 or the destination
   platform is not Windows 2000 on a Pentium 4).
   
   The user should be aware of the precision of these types, when
   these types are changed! For instance, when the destination platform 
   is a particular 8051 that does not support any doubles at all,
   one might change the YAW_XXDouble type into some float of 4 bytes.
   The results may then differ from the 20-sim results. It is advised
   to check these differences by running the code with both settings
   on the PC first (as far as this is possible).
   
   In 20-sim the following definitions are used:
   
    typedef YAW_XXDouble double;
    typedef YAW_XXInteger int;
   
   so that 
   
    YAW_XXDouble is 8 bytes (64 bits) with a range of [-1.7E+308, 1.7E+308]
    YAW_XXInteger is 4 bytes (32 bits) with a range of [-2147483648, 2147483647]
    YAW_XXCharacter is 1 byte (8 bits) with a value of [0, 255]
    YAW_XXBoolean is 1 byte (8 bits) with a value of 0 or 1
*/ 

#ifndef YAW_XX_TYPES_H
#define YAW_XX_TYPES_H

/* The mentioned typedefs */
typedef double YAW_XXDouble;
typedef int YAW_XXInteger;
typedef char YAW_XXCharacter;
typedef char YAW_XXBoolean;
typedef const char* YAW_XXString;

/* Defines */
#define YAW_XXTRUE  1
#define YAW_XXFALSE 0

#endif

