/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yaw_xxmodel.h
 *  subm:  PositionControllerPan
 *  model: PositionControllerPan
 *  expmt: Jiwy-1
 *  date:  June 2, 2025
 *  time:  10:24:36 AM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the yaw_xxmodel.c file
*/

#ifndef YAW_XX_MODEL_H
#define YAW_XX_MODEL_H

/* Our own include files */
#include "yaw_xxtypes.h"

/* Simulation variables */
extern YAW_XXDouble yaw_xx_start_time;
extern YAW_XXDouble yaw_xx_finish_time;
extern YAW_XXDouble yaw_xx_step_size;
extern YAW_XXDouble yaw_xx_time;
extern YAW_XXInteger yaw_xx_steps;
extern YAW_XXBoolean yaw_xx_initialize;
extern YAW_XXBoolean yaw_xx_major;
extern YAW_XXBoolean yaw_xx_stop_simulation;

/* Model size constants */
#define yaw_xx_constants_size 0
#define yaw_xx_parameters_size 7
#define yaw_xx_initialvalues_size 3
#define yaw_xx_variables_size 10
#define yaw_xx_states_size 3

/* Variable arrays */
extern YAW_XXDouble yaw_xx_P[];
extern YAW_XXDouble yaw_xx_I[];
extern YAW_XXDouble yaw_xx_V[];
extern YAW_XXDouble yaw_xx_s[];
extern YAW_XXDouble yaw_xx_R[];


/* The names of the variables as used in the arrays above
   uncomment this if you need the names (see source file too)
extern YAW_XXString yaw_xx_parameter_names[];
extern YAW_XXString yaw_xx_initial_value_names[];
extern YAW_XXString yaw_xx_variable_names[];
extern YAW_XXString yaw_xx_state_names[];
extern YAW_XXString yaw_xx_rate_names[];
*/

/* Initialization methods */
/* Initialize complete model */
void YAW_XXModelInitialize (void);
/* Initialize specific model values */
void YAW_XXModelInitialize_parameters(void);
void YAW_XXModelInitialize_initialvalues(void);
void YAW_XXModelInitialize_states(void);
void YAW_XXModelInitialize_variables(void);
void YAW_XXModelTerminate (void);

/* Computation methods */
void YAW_XXCalculateInitial (void);
void YAW_XXCalculateStatic (void);
void YAW_XXCalculateInput (void);
void YAW_XXCalculateDynamic (void);
void YAW_XXCalculateOutput (void);
void YAW_XXCalculateFinal (void);


#endif

