/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yaw_xxsubmod.h
 *  subm:  PositionControllerPan
 *  model: PositionControllerPan
 *  expmt: Jiwy-1
 *  date:  June 2, 2025
 *  time:  10:24:36 AM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the yaw_xxmodel.c file
*/

#ifndef YAW_XX_SUBMOD_H
#define YAW_XX_SUBMOD_H

/* Our own include files */
#include "yaw_xxmodel.h"

/* Submodel I/O variables */
extern YAW_XXInteger yaw_xx_number_of_inputs;
extern YAW_XXInteger yaw_xx_number_of_outputs;

/* The names of the variables as used in the arrays above */
extern YAW_XXString yaw_xx_input_names[];
extern YAW_XXString yaw_xx_output_names[];


/* The submodel functions */
void YAW_XXInitializeSubmodel (YAW_XXDouble *u, YAW_XXDouble *y, YAW_XXDouble t);
void YAW_XXCalculateSubmodel (YAW_XXDouble *u, YAW_XXDouble *y, YAW_XXDouble t);
void YAW_XXTerminateSubmodel (YAW_XXDouble *u, YAW_XXDouble *y, YAW_XXDouble t);
void YAW_XXCopyInputsToVariables (YAW_XXDouble *u);
void YAW_XXCopyVariablesToOutputs (YAW_XXDouble *y);

#endif

